services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    links:
      - database
  
  database:
    image: postgres:12-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: todos
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todos
